[phases.setup]
nixPkgs = [
    "python313",
    "python313Packages.pip",
    "postgresql",
    "postgresql.lib",
    "libpqxx",
    "gcc",
    "libffi",
    "openssl",
    "zlib"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python bot.py"

[variables]
TOKEN.default = "8374994781:AAEyHplC_nJlyIeBCt3RJGHBfBOoT2r4Agw"
ADMIN_ID.default = "5528629749"

[environments]
TOKEN.required = true
ADMIN_ID.required = true
DATABASE_URL.required = false
