[phases.setup]
nixPkgs = [
    "python311",
    "postgresql",
    "gcc",
    "libffi",
    "openssl"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python bot.py"

[environments]
TOKEN.required = true
ADMIN_ID.required = true
DATABASE_URL.required = false
